[package]
name = "imagecli"
version = "0.1.0"
edition = "2024"

[lib]
name = "imagix"
path = "src/imagix/mod.rs"

[[bin]]
name = "imagecli"
path = "src/imagecli.rs"

[dependencies]
image = "0.25.8"
structopt="0.3.26"
thiserror = "2.0.17"

[dev-dependencies]
rstest = "0.26.1"